# Generated by Django 3.0.5 on 2020-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='b_or_r',
            field=models.BooleanField(default=True, help_text='Checked is Boast, Unchecked is Roast'),
        ),
    ]
