# Generated by Django 3.0.5 on 2020-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20200513_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='b_or_r',
            field=models.BooleanField(help_text='Checked is Boast, Unchecked is Roast'),
        ),
    ]
